spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?schema=chery
    username: postgres
    password: postgres

  liquibase:
    enabled: false
    change-log: classpath:/db/changelog/db.changelog-master.yaml
